#!/usr/bin/env python
import os, array, sys
import pagemap

kpmap = pagemap.kpagemap()
krange = kpmap.counts(0, kpmap.pages())

def measure(pid):
    vss, rss, uss, pss = 0, 0, 0, 0
    pmap = pagemap.processmap(pid)

    for m in pmap.maps():
        vss += m.end - m.start
        r = pmap.range(m.start, m.end)
        for pfn in r:
            if pfn == -1:
                continue
            rss += 4096
            c = krange[pfn]
            if c == 1:
                uss += 4096
            pss += int(4096.0 / c)

    return vss, rss, pss, uss

for pid in sys.argv[1:]:
    vss, rss, pss, uss = measure(int(pid))
    print "%8d: VSS % 7dk RSS % 7dk PSS % 7dk USS % 7dk" % (
        int(pid),
        vss / 1024,
        rss / 1024,
        pss / 1024,
        uss / 1024)
